### ISSUE TITLE
Summary of the presentations, what needs to be done

### ISSUE THREAD

**Issue by lamblin** [mila-udem/summerschool2015#1]
## 0. Before the summer school
- [x] Add installation instructions (#5)
## 1. Intro to Theano

First session:
- [x] Slides: intro to Theano (1h) (#7)
- [x] Notebook: logistic regression, SGD (30 min)
## 2. Fuel, Deep MLP

Second session:
- [x] ~~Slides: intro to Fuel (30 min) (https://github.com/mila-udem/fuel/issues/195)~~ (no slides)
- [x] Notebook: Fuel (30 min) (https://github.com/mila-udem/fuel/issues/195, #2)
- [x] Notebook: DAE, deep MLP (30 min) (#11)
## 3. Debugging, ConvNets

Third session:
- [x] Notebook: Debugging tools in Theano (30 min)
- [x] Slides: Convolution (30 min) (#6)
- [x] Notebook: ConvNets + Fuel (30 min) (#3)
## 4. Scan, RNN

Fourth session:
- [x] Notebook: Scan (30 min)
- [x] Notebook: RNN, LSTM (1 h)

**Comment by nouiz** [comment]
On the debugging tools, we have slides and notebook with exercies.
